#!/usr/bin/env python3
"""Build layers/index.json: the routing table the layer-autoload hook reads.

Run from the repo root after adding or changing a layer's frontmatter:

    python3 scripts/build_layer_index.py          # rewrite layers/index.json
    python3 scripts/build_layer_index.py --check  # exit 1 if it is stale (CI)

The hook runs on every Read/Edit/Write, so it must not parse YAML (PyYAML may
be missing on the user's machine). This script does the parsing once, at build
time, and records only what routing needs.

Only background layers are indexed: a layer with no `paths:` (the
user-invocable command layers) can never be routed by file, so it is left out.
"""
import glob
import json
import os
import sys

import yaml

INDEX = "layers/index.json"

# Source-file extension -> language family. Shared with the hook, which only
# loads a layer for a source file when the file's family is one of the layer's.
EXT_LANG = {
    "ts": "js", "tsx": "js", "js": "js", "jsx": "js", "mjs": "js", "cjs": "js", "vue": "js", "svelte": "js", "astro": "js",
    "py": "python", "dart": "dart", "cs": "dotnet", "csproj": "dotnet",
}
# Layers whose globs name no source extension but whose rules are for one language.
STACK_LANG = {"ci/flutter-release": ["dart"], "i18n/flutter-l10n": ["dart"], "mobile/flutter": ["dart"]}


def languages(stack, paths):
    """Language families a layer's rules are written for. Globs with source
    extensions decide; otherwise STACK_LANG; otherwise JS/TS, which is what
    every other layer's code samples are written in."""
    if stack in STACK_LANG:
        return STACK_LANG[stack]
    found = sorted({EXT_LANG[ext] for p in paths
                    for ext in [p.rsplit(".", 1)[-1].strip('"')] if "." in p and ext in EXT_LANG})
    return found or ["js"]


def frontmatter(path):
    text = open(path, encoding="utf-8").read()
    if not text.startswith("---"):
        return None
    try:
        d = yaml.safe_load(text.split("---")[1])
    except yaml.YAMLError:
        return None
    return d if isinstance(d, dict) else None


def detail_file(layer_dir, name):
    """The file layer-consultant would load: <name>.md, else the one other .md."""
    preferred = os.path.join(layer_dir, f"{name}.md")
    if os.path.isfile(preferred):
        return preferred
    others = sorted(
        f for f in glob.glob(os.path.join(layer_dir, "*.md"))
        if os.path.basename(f) not in ("SKILL.md", "README.md")
    )
    return others[0] if len(others) == 1 else None


def build():
    layers = []
    for skill in sorted(glob.glob("layers/**/SKILL.md", recursive=True)):
        d = frontmatter(skill)
        if not d or not d.get("paths"):
            continue
        layer_dir = os.path.dirname(skill)
        paths = d["paths"] if isinstance(d["paths"], list) else [d["paths"]]
        detail = detail_file(layer_dir, d.get("name", ""))
        layers.append({
            "name": d.get("name") or os.path.basename(layer_dir),
            "stack": d.get("stack") or "",
            "dir": layer_dir,
            "paths": [str(p) for p in paths],
            "langs": languages(d.get("stack") or "", [str(p) for p in paths]),
            "detail": detail,
        })
    return {
        "_comment": "Generated by scripts/build_layer_index.py; do not edit by hand.",
        "layers": layers,
    }


def main():
    rendered = json.dumps(build(), indent=1, ensure_ascii=False) + "\n"
    if "--check" in sys.argv:
        current = open(INDEX, encoding="utf-8").read() if os.path.exists(INDEX) else ""
        if current != rendered:
            print(f"{INDEX} is stale. Run: python3 scripts/build_layer_index.py")
            sys.exit(1)
        print(f"{INDEX} is up to date.")
        return
    open(INDEX, "w", encoding="utf-8").write(rendered)
    print(f"Wrote {INDEX} ({len(json.loads(rendered)['layers'])} layers).")


if __name__ == "__main__":
    main()
