#!/usr/bin/env python3
"""Generate layers/**/README.md from each layer's SKILL.md frontmatter.

Run from the repo root after adding or changing a layer:

    python3 scripts/build_layer_readmes.py          # rewrite the READMEs
    python3 scripts/build_layer_readmes.py --check  # exit 1 if any is stale (CI)

The README is what someone browsing the repo on GitHub sees for a layer, so it
must say what the layer is and when it loads. Hand-written READMEs drifted (#102);
these are rebuilt from the same frontmatter the layer-autoload hook uses.

Folders with no SKILL.md (planned layers) keep their hand-written README.
"""
import glob
import os
import sys

import yaml

MARKER = "<!-- Generated by scripts/build_layer_readmes.py from SKILL.md; do not edit by hand. -->"


def frontmatter(path):
    text = open(path, encoding="utf-8").read()
    if not text.startswith("---"):
        return {}
    try:
        d = yaml.safe_load(text.split("---")[1])
    except yaml.YAMLError:
        return {}
    return d if isinstance(d, dict) else {}


def file_role(name, detail):
    if name == "SKILL.md":
        return "short summary Claude gets when the layer loads"
    if name == detail:
        return "full standards"
    if name.endswith(".eval.yaml"):
        return "eval cases (run with `/eval`)"
    if name.endswith(".md"):
        return "reference"
    return ""


def render(layer_dir, d):
    name = d.get("name") or os.path.basename(layer_dir)
    rel = layer_dir.replace(os.sep, "/")
    lines = [MARKER, f"# {rel}/", "", str(d.get("description", "")).strip(), ""]
    facts = [f"**Skill:** `{name}`"]
    if d.get("stack"):
        facts.append(f"**Stack:** `{d['stack']}`")
    lines += [" · ".join(facts), ""]

    paths = d.get("paths")
    if paths:
        paths = paths if isinstance(paths, list) else [paths]
        lines += ["**Loads automatically** when Claude reads or edits a file matching:", ""]
        lines += [f"- `{p}`" for p in paths]
        lines += ["", "Layers that contradict the project's stack (`stack.json`, `package.json`) are skipped."]
    elif d.get("user-invocable"):
        lines += [f"**Command:** run `/{name}` in Claude Code."]
    else:
        lines += ["Loaded on demand by other layers or skills."]
    lines.append("")

    files = sorted(f for f in os.listdir(layer_dir)
                   if os.path.isfile(os.path.join(layer_dir, f)) and f != "README.md")
    docs = [f for f in files if f.endswith(".md") and f != "SKILL.md"]
    detail = f"{name}.md" if f"{name}.md" in docs else (docs[0] if len(docs) == 1 else None)
    if files:
        lines += ["**Files:**", ""]
        for f in files:
            role = file_role(f, detail)
            lines.append(f"- [`{f}`]({f})" + (f": {role}" if role else ""))
        lines.append("")

    subs = sorted(s for s in os.listdir(layer_dir) if os.path.isfile(os.path.join(layer_dir, s, "SKILL.md")))
    if subs:
        lines += ["**Sub-layers:** " + ", ".join(f"[`{s}`]({s}/)" for s in subs), ""]

    depth = rel.count("/") + 1
    lines.append(f"Contribute: see [CONTRIBUTING.md]({'../' * depth}CONTRIBUTING.md).")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    stale = []
    for skill in sorted(glob.glob("layers/**/SKILL.md", recursive=True)):
        layer_dir = os.path.dirname(skill)
        want = render(layer_dir, frontmatter(skill))
        path = os.path.join(layer_dir, "README.md")
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            continue
        stale.append(path)
        if not check:
            open(path, "w", encoding="utf-8").write(want)
    if check:
        if stale:
            print(f"{len(stale)} layer README(s) are stale, e.g. {stale[0]}. Run: python3 scripts/build_layer_readmes.py")
            sys.exit(1)
        print("Layer READMEs are up to date.")
    else:
        print(f"Wrote {len(stale)} layer README(s).")


if __name__ == "__main__":
    main()
